services:
  db:
      image: postgres
      restart: always
      volumes:
          - db-data:/var/lib/postgresql/data
          - ./docker_scripts:/docker-entrypoint-initdb.d
      environment:
          - POSTGRES_DB=sqlytes-inventory-app
          - POSTGRES_USER=docker_admin
          - POSTGRES_PASSWORD=postgresadmin
      ports:
          - "5432:5432"
volumes:
  db-data: